metadata:
  description: config for Smoke and Dust, RRFS_CONUS_3km
user:
  RUN_ENVIR: community
  MACHINE: hera
  ACCOUNT: [account name]
workflow:
  USE_CRON_TO_RELAUNCH: true
  CRON_RELAUNCH_INTVL_MNTS: 3
  EXPT_SUBDIR: smoke_dust_conus3km
  PREDEF_GRID_NAME: RRFS_CONUS_3km
  CCPP_PHYS_SUITE: FV3_HRRR_gf
  DATE_FIRST_CYCL: '2019072200'
  DATE_LAST_CYCL: '2019072206'
  INCR_CYCL_FREQ: 6
  FCST_LEN_HRS: 6
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  DEBUG: false
  COMPILER: intel
  DIAG_TABLE_TMPL_FN: diag_table_smoke_dust.FV3_HRRR_gf
  FIELD_TABLE_TMPL_FN: field_table_smoke_dust.FV3_HRRR_gf
  DO_REAL_TIME: false
  COLDSTART: true      # set to true for cold start
  WARMSTART_CYCLE_DIR: '/scratch2/NAGAPE/epic/SRW-AQM_DATA/aqm_data/restart/2023111000' # for hera
nco:
  envir_default: test_smoke_dust
  NET_default: smoke_dust
  RUN_default: smoke_dust
rocoto:
  tasks:
    taskgroups: '{{ ["parm/wflow/prep.yaml", "parm/wflow/smoke_dust_prep.yaml", "parm/wflow/coldstart.yaml", "parm/wflow/post.yaml"]|include }}'
    metatask_run_ensemble:
      task_run_fcst_mem#mem#:
        walltime: 03:00:00
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: RAP
  EXTRN_MDL_ICS_OFFSET_HRS: 0
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: RAP
  LBC_SPEC_INTVL_HRS: 6
  EXTRN_MDL_LBCS_OFFSET_HRS: 0
task_run_fcst:
  DT_ATMOS: 36
  LAYOUT_X: 15
  LAYOUT_Y: 20
  BLOCKSIZE: 32
  WRTCMP_write_tasks_per_group: 40
  RESTART_INTERVAL: 6 12 18 24
  QUILTING: true
  PRINT_ESMF: false
  DO_FCST_RESTART: false
task_run_post:
  POST_OUTPUT_DOMAIN_NAME: conus3km
  USE_CUSTOM_POST_CONFIG_FILE: false
global:
  DO_ENSEMBLE: false
  NUM_ENS_MEMBERS: 2
  HALO_BLEND: 0
smoke_dust_parm:
  DO_SMOKE_DUST: true

